# NumPy

<b> Note </b> The content of this notebook is mainly based on NumPy tutorial.<br>
<a href="https://www.numpy.org/devdocs/user/quickstart.html">NumPy tutorial</a>

NumPy is the fundamental package for scientific computing with Python.

It provides highly optimised implementations of the fundamental datatypes for linear algebra : vectors, matrices, and in general higher-dimensional arrays.

Most of the scientific packages (example : SciPy library) and applications for Python is built on top of NumPy.


### Importing numpy ###

It's a common way to import numpy and rename it as <b>np</b>.

In [1]:
import numpy as np

## NumPy Arrays ##
NumPy provides a multidimensional array class (<b>numpy.ndarray</b> and many functions and methods that handle.

An object instance of ndarray is a table of homogeneous elements (usually numbers), all of the same type, indexed by a tuple of positive integers.<br>
In NumPy dimensions are called axes.

### Array Creation ###

There are several ways to create numpy arrays:


In [2]:
a = np.array([1, 3, 5, 7])
a

array([1, 3, 5, 7])

In [3]:
print(a)
type(a)

[1 3 5 7]


numpy.ndarray

#### Main differences from Python lists ####
* Much Faster !
* Fixed datatype (all elements have the same datatype)
* Fixed size (all elements have the same size)

In [4]:
a = np.array([1, 2.5, 3, 4.5])
print(a)
a.dtype

[1.  2.5 3.  4.5]


dtype('float64')

In [5]:
a = np.array( [ [1,2], [3,4] ])
print(a)
a.dtype

[[1 2]
 [3 4]]


dtype('int64')

The type of the array can also be explicitly specified at creation time :

In [6]:
a = np.array( [ [1,2], [3,4] ], dtype='float64')
print(a)
a.dtype

[[1. 2.]
 [3. 4.]]


dtype('float64')

### Array Object attributes ###
The more important attributes of an ndarray object are: ```ndim, shape, size, dtype, itemsize, data```

In [7]:
b = np.array([[1.0, 2, 3], [4, 8, 10]])
print("b = ", b)
print("number of axes = ", b.ndim)
print("dimensions = ", b.shape)
print("total number of elements = ", b.size)
print("type of elements = ", b.dtype)
print("size in bytes of each element = ", b.itemsize)
print("memory adress = ", b.data)

b =  [[ 1.  2.  3.]
 [ 4.  8. 10.]]
number of axes =  2
dimensions =  (2, 3)
total number of elements =  6
type of elements =  float64
size in bytes of each element =  8
memory adress =  <memory at 0x10fbec1f8>


In [8]:
a = np.zeros((3, 4))
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [9]:
b = np.zeros((4, 2, 3))
print(b)

[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]


In [10]:
b.shape

(4, 2, 3)

In [11]:
a = np.ones((3, 4))
print(a)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [12]:
b = np.ones((4, 2, 3), dtype='float32')
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [13]:
a = np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
a = np.diag([1., 2, 3, 4])
print(a)

Create array with random elements : 

In [14]:
a = np.random.random((3,3))
print(a)

[[0.91238935 0.97379032 0.78249132]
 [0.85715413 0.45826007 0.53430272]
 [0.8533621  0.49424295 0.0116734 ]]


For random samples from $ N(\mu, \sigma^2) $ 
use: ``` sigma * np.random.randn(...) + mu ```

In [15]:
x = 5.0 * np.random.randn(4, 4) + 2.0
print(x)

[[  6.86215849   7.68577393  -4.21511638  -0.4805879 ]
 [ -2.09694394  -5.04160386 -13.7976499    1.13161668]
 [ -0.17016679  -1.26708797  -1.45800087   0.85447965]
 [  6.78154712   0.36988682   4.67540033   4.38424886]]


To create sequences of numbers, NumPy provides the function ``` arange ``` analogous to ``` range ``` that returns arrays instead of lists.<br>
In addition ``` arange ``` accepts float arguments.

In [16]:
a = np.arange(10, 20)
print(a)

[10 11 12 13 14 15 16 17 18 19]


In [17]:
a = np.arange(10, 20, 0.5)
print(a)

[10.  10.5 11.  11.5 12.  12.5 13.  13.5 14.  14.5 15.  15.5 16.  16.5
 17.  17.5 18.  18.5 19.  19.5]


In [18]:
a = np.arange(20).reshape(4, 5)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [19]:
a = np.arange(0, 1, 0.1)
print(a)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


Another function to create sequences of numbers is ``` linspace ```. It receives as an argument the number of elements that we want, instead of the step.

In [20]:
a = np.linspace(0, 1, 10)
print(a)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [21]:
x = np.linspace(0, 2*np.pi, 100)
y = np.sin(x)
print(x.shape)
print(x.ndim)
print(y.shape)
print(x.ndim)
print(y.ndim)
print(x[:5])
print(y[:5])

(100,)
1
(100,)
1
1
[0.         0.06346652 0.12693304 0.19039955 0.25386607]
[0.         0.06342392 0.12659245 0.18925124 0.25114799]


```logspace``` is also a useful function :

In [22]:
x = np.logspace(-6, 6, 5)
print(x)
y = np.log10(x)
print(y)

[1.e-06 1.e-03 1.e+00 1.e+03 1.e+06]
[-6. -3.  0.  3.  6.]


## Indexing, Slicing ##
* One-dimensional arrays can be indexed, sliced and iterated over, much like lists and other Python sequences.
* Multidimensional arrays can have one index per axis. These indices are given in a tuple separated by commas.

In [23]:
a = np.arange(10, 20)
print(a)

[10 11 12 13 14 15 16 17 18 19]


In [24]:
a[0]

10

In [25]:
a[len(a) - 1]

19

In [26]:
a[3:7]

array([13, 14, 15, 16])

In [27]:
b = np.arange(12).reshape(3, 4)
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [28]:
c = np.arange(12).reshape(2, 3, 2)
print(c)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]


In [29]:
b[0, 0]

0

In [30]:
b[2, 3]

11

In [31]:
b[2][3]

11

In [32]:
b[1:3, 2:4]

array([[ 6,  7],
       [10, 11]])

In [33]:
a = np.arange(90).reshape(10, 9)
print(a)

[[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24 25 26]
 [27 28 29 30 31 32 33 34 35]
 [36 37 38 39 40 41 42 43 44]
 [45 46 47 48 49 50 51 52 53]
 [54 55 56 57 58 59 60 61 62]
 [63 64 65 66 67 68 69 70 71]
 [72 73 74 75 76 77 78 79 80]
 [81 82 83 84 85 86 87 88 89]]


In [35]:
y = a[:, a.shape[1]-1]
print(y)
X = a[:, :a.shape[1]-1]
print(X)

[ 8 17 26 35 44 53 62 71 80 89]
[[ 0  1  2  3  4  5  6  7]
 [ 9 10 11 12 13 14 15 16]
 [18 19 20 21 22 23 24 25]
 [27 28 29 30 31 32 33 34]
 [36 37 38 39 40 41 42 43]
 [45 46 47 48 49 50 51 52]
 [54 55 56 57 58 59 60 61]
 [63 64 65 66 67 68 69 70]
 [72 73 74 75 76 77 78 79]
 [81 82 83 84 85 86 87 88]]


In [36]:
b = a[:, (1, 3, 5)]
print(b)

[[ 1  3  5]
 [10 12 14]
 [19 21 23]
 [28 30 32]
 [37 39 41]
 [46 48 50]
 [55 57 59]
 [64 66 68]
 [73 75 77]
 [82 84 86]]


## Basic Operations on arrays ##

Arithmetic operators (+, -, \*, /, \**, <, >, <=, >=, ==, !=, ... ) on arrays apply elementwise (element by element).<br>
A new array is created and filled with the result.


In [37]:
a = np.array([[1, 3], [2, 4]])
print(a)
b = np.array([[10, 30], [20, 40]])
print(b)

[[1 3]
 [2 4]]
[[10 30]
 [20 40]]


In [38]:
c = a + 2
print(c)

[[3 5]
 [4 6]]


In [39]:
c = a * 2
print(c)

[[2 6]
 [4 8]]


In [40]:
c = a ** 2
print(c)

[[ 1  9]
 [ 4 16]]


In [41]:
c = a + b
print(c)

[[11 33]
 [22 44]]


In [42]:
c = b-a
print(c)

[[ 9 27]
 [18 36]]


In [43]:
c = a*b
print(c)

[[ 10  90]
 [ 40 160]]


In [44]:
c = a/b
print(c)

[[0.1 0.1]
 [0.1 0.1]]


In [45]:
c = 1.0 / b
print(c)

[[0.1        0.03333333]
 [0.05       0.025     ]]


In [46]:
c = b < 25
print(c)

[[ True False]
 [ True False]]


## Broadcasting ##
A very important concept to understand in numpy is "broadcasting". It is very useful for performing mathematical operations between arrays of different shapes.

Here is an illustrative example : 

<img src="python_broadcasting.PNG" style="width:400px;">

<i>Source : P. E. Farrell (Oxford)</i>

In [47]:
x = np.arange(3) + 5
print(x)

[5 6 7]


In [48]:
y = np.ones((3,3)) + np.arange(3)
print(y)

[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]


In [49]:
z = np.arange(3).reshape(3, 1) + np.arange(3)
print(z)

[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [50]:
a = np.ones((3, 3, 3)) + np.arange(3)
print(a)

[[[1. 2. 3.]
  [1. 2. 3.]
  [1. 2. 3.]]

 [[1. 2. 3.]
  [1. 2. 3.]
  [1. 2. 3.]]

 [[1. 2. 3.]
  [1. 2. 3.]
  [1. 2. 3.]]]


### sum, min, max, ... ###

In [51]:
a = np.arange(12).reshape(3,4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [52]:
print(a.sum())
print(a.min())
print(a.max())

66
0
11


Operate on each column

In [53]:
print(a.sum(axis=0))
print(a.min(axis=0))
print(a.max(axis=0))

[12 15 18 21]
[0 1 2 3]
[ 8  9 10 11]


Operate on each row

In [54]:
print(a.sum(axis=1))
print(a.min(axis=1))
print(a.max(axis=1))


[ 6 22 38]
[0 4 8]
[ 3  7 11]


## Usual mathematical functions ##
Mathematical functions such as sin, cos, tan, exp, log, sqrt ... operate elementwise on an array, producing an array as output.<br>
In NumPy, these are called **universal functions** (ufunc)

In [55]:
x = np.array([1, 2, 3])
print(np.exp(x))
print(np.sin(x))

[ 2.71828183  7.3890561  20.08553692]
[0.84147098 0.90929743 0.14112001]


**Example**: Implement the sigmoid function using math and then numpy. 

$$ \text{For } x \in \mathbb{R}^n \text{,     } sigmoid(x) = sigmoid\begin{pmatrix}
    x_1  \\
    x_2  \\
    ...  \\
    x_n  \\
\end{pmatrix} = \begin{pmatrix}
    \frac{1}{1+e^{-x_1}}  \\
    \frac{1}{1+e^{-x_2}}  \\
    ...  \\
    \frac{1}{1+e^{-x_n}}  \\
\end{pmatrix} $$

In [56]:
import math
def sigmoid (x):
    return 1.0 / (1.0 + math.exp(-x))

In [57]:
x = 1.5
sigmoid(x)

0.8175744761936437

In [58]:
x = np.random.random(3)
print(x)
sigmoid(x)

[0.74659626 0.27022575 0.04248098]


TypeError: only size-1 arrays can be converted to Python scalars

In [59]:
sigmoid = np.vectorize(sigmoid)

In [60]:
x = np.random.random(3)
print(x)
sigmoid(x)

[0.75676336 0.19564028 0.52063066]


array([0.68065061, 0.54875466, 0.62729522])

In [61]:
def sigmoid (x):
    return 1.0/(1.0 + np.exp(-x))

In [62]:
x = 1.5
sigmoid(x)

0.8175744761936437

In [63]:
x = np.random.random(3)
print(x)
sigmoid(x)

[0.15035973 0.16958813 0.78604007]


array([0.53751927, 0.54229571, 0.68698043])

**Exercise**: Implement a softmax function using numpy.

**Def**:
- $ \text{for } x \in \mathbb{R}^{1\times n} \text{,     } softmax(x) = softmax(\begin{bmatrix}
    x_1  &&
    x_2 &&
    ...  &&
    x_n  
\end{bmatrix}) = \begin{bmatrix}
     \frac{e^{x_1}}{\sum_{j}e^{x_j}}  &&
    \frac{e^{x_2}}{\sum_{j}e^{x_j}}  &&
    ...  &&
    \frac{e^{x_n}}{\sum_{j}e^{x_j}} 
\end{bmatrix} $ 

- $\text{for a matrix } x \in \mathbb{R}^{m \times n} \text{,  $x_{ij}$ maps to the element in the $i^{th}$ row and $j^{th}$ column of $x$, thus we have: }$  $$softmax(x) = softmax\begin{bmatrix}
    x_{11} & x_{12} & x_{13} & \dots  & x_{1n} \\
    x_{21} & x_{22} & x_{23} & \dots  & x_{2n} \\
    \vdots & \vdots & \vdots & \ddots & \vdots \\
    x_{m1} & x_{m2} & x_{m3} & \dots  & x_{mn}
\end{bmatrix} = \begin{bmatrix}
    \frac{e^{x_{11}}}{\sum_{j}e^{x_{1j}}} & \frac{e^{x_{12}}}{\sum_{j}e^{x_{1j}}} & \frac{e^{x_{13}}}{\sum_{j}e^{x_{1j}}} & \dots  & \frac{e^{x_{1n}}}{\sum_{j}e^{x_{1j}}} \\
    \frac{e^{x_{21}}}{\sum_{j}e^{x_{2j}}} & \frac{e^{x_{22}}}{\sum_{j}e^{x_{2j}}} & \frac{e^{x_{23}}}{\sum_{j}e^{x_{2j}}} & \dots  & \frac{e^{x_{2n}}}{\sum_{j}e^{x_{2j}}} \\
    \vdots & \vdots & \vdots & \ddots & \vdots \\
    \frac{e^{x_{m1}}}{\sum_{j}e^{x_{mj}}} & \frac{e^{x_{m2}}}{\sum_{j}e^{x_{mj}}} & \frac{e^{x_{m3}}}{\sum_{j}e^{x_{mj}}} & \dots  & \frac{e^{x_{mn}}}{\sum_{j}e^{x_{mj}}}
\end{bmatrix} $$

In [64]:
def softmax(x):
    y = np.exp(x)
    s = x.sum(axis=1)
    return y / s.reshape(x.shape[0], 1)

In [65]:
x = np.arange(12).reshape(3, 4)
print(x)
y = np.exp(x)
print(y)
s = x.sum(axis=1).reshape(3, 1)
print(s)
print(s.shape)
y = y/s
print(y)
y = softmax(x)
print(y)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03]
 [2.98095799e+03 8.10308393e+03 2.20264658e+04 5.98741417e+04]]
[[ 6]
 [22]
 [38]]
(3, 1)
[[1.66666667e-01 4.53046971e-01 1.23150935e+00 3.34758949e+00]
 [2.48173409e+00 6.74605269e+00 1.83376724e+01 4.98469617e+01]
 [7.84462628e+01 2.13239051e+02 5.79643837e+02 1.57563531e+03]]
[[1.66666667e-01 4.53046971e-01 1.23150935e+00 3.34758949e+00]
 [2.48173409e+00 6.74605269e+00 1.83376724e+01 4.98469617e+01]
 [7.84462628e+01 2.13239051e+02 5.79643837e+02 1.57563531e+03]]


## Linear Algebra ##

In [66]:
a = np.arange(1, 13).reshape(3, 4)
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [67]:
a.transpose()

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [68]:
a.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [69]:
a.trace()

18

In [70]:
b = np.arange(1, 10).reshape(3, 3)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [71]:
c = b.dot(a)
print(c)

[[ 38  44  50  56]
 [ 83  98 113 128]
 [128 152 176 200]]


In [72]:
c = np.dot(b, a)
print(c)

[[ 38  44  50  56]
 [ 83  98 113 128]
 [128 152 176 200]]


In [73]:
c = b @ a  # Python 3.5 and higher
print(c)

[[ 38  44  50  56]
 [ 83  98 113 128]
 [128 152 176 200]]


In [74]:
from numpy import linalg

In [75]:
linalg.inv(b)

array([[ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15],
       [-6.30503948e+15,  1.26100790e+16, -6.30503948e+15],
       [ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15]])

In [76]:
linalg.det(b)

-9.51619735392994e-16

In [77]:
linalg.matrix_rank(b)

2

In [78]:
linalg.eigvals(b)

array([ 1.61168440e+01, -1.11684397e+00, -9.75918483e-16])

In [79]:
linalg.eig(b)

(array([ 1.61168440e+01, -1.11684397e+00, -9.75918483e-16]),
 array([[-0.23197069, -0.78583024,  0.40824829],
        [-0.52532209, -0.08675134, -0.81649658],
        [-0.8186735 ,  0.61232756,  0.40824829]]))

In [80]:
linalg.svd(b)

(array([[-0.21483724,  0.88723069,  0.40824829],
        [-0.52058739,  0.24964395, -0.81649658],
        [-0.82633754, -0.38794278,  0.40824829]]),
 array([1.68481034e+01, 1.06836951e+00, 3.33475287e-16]),
 array([[-0.47967118, -0.57236779, -0.66506441],
        [-0.77669099, -0.07568647,  0.62531805],
        [-0.40824829,  0.81649658, -0.40824829]]))

In [81]:
x = np.array([1, 2, 3])
y = linalg.solve(b, x)
print(y)

[-0.23333333  0.46666667  0.1       ]


## Vectorization

In general, when using NumPy, you want to avoid loops over elements on an array.<br>
To make sure that your code is computationally efficient, you will use vectorization.

Let look at this example :



In [83]:
from time import time

n = 5000

x = np.random.random(n)
y = np.random.random(n)

## without vectrization
begin = time()
A = np.zeros((n, n))
for i in range(len(x)):
    for j in range(len(y)):
        A[i, j] = x[i] * y[j]
end = time()
print ("Computation time = " + str(1000*(end - begin)) + " ms")

## with vectrization
begin = time()
B = np.dot(x.transpose(), y)
end = time()
print ("Computation time = " + str(1000*(end - begin)) + " ms")


Computation time = 18058.617115020752 ms
Computation time = 0.3490447998046875 ms


### Exercise ### 

**1-** Implement the numpy vectorized version of the L1 loss.

- L1 loss is defined as:
$$\begin{align*} & L_1(\hat{y}, y) = \sum_{i=0}^m|y^{(i)} - \hat{y}^{(i)}| \end{align*}$$


**2-** Implement the numpy vectorized version of the L2 loss. 

- L2 loss is defined as $$\begin{align*} & L_2(\hat{y},y) = \sum_{i=0}^m(y^{(i)} - \hat{y}^{(i)})^2 \end{align*}$$

## Shape manipulation

<img src="numpy_arrays.png" style="width:500px;"/>
<i>Source : T. Oliphant</i>

In [84]:
a = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [85]:
a.shape

(3, 3)

In [86]:
b = a.flatten()
print(b)

[0 1 2 3 4 5 6 7 8]


In [87]:
b.shape

(9,)

In [88]:
a = np.arange(1, 25)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


In [89]:
b = a.reshape(4, 6)
print(b)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]


In [90]:
b = a.reshape(2, 3, 4)
print(b)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [91]:
c = b.ravel()
print(c)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


In [92]:
c.shape

(24,)

In [93]:
c[0] = 100

In [94]:
a

array([100,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24])

In [95]:
c

array([100,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24])